name: pyramm

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black
        pip install .
    - name: Run black format
      run: black .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 100 chars wide
        flake8 . --count --exit-zero --max-complexity=12 --max-line-length=100 --statistics
    - name: Test with pytest
      env:
        RAMM_USERNAME: ${{ secrets.RAMM_USERNAME }}
        RAMM_PASSWORD: ${{ secrets.RAMM_PASSWORD }}
      run: |
        pytest -v tests/
